const DICT = {
  "hello":{p:"HH AH0 L OW1",m:"你好",e:"Hello, how are you?",z:"哈囉"},
  "goodbye":{p:"G UH1 D B AY1",m:"再見",e:"Goodbye, see you tomorrow.",z:"固拜"},
  "thank":{p:"TH AE1 NG K",m:"謝謝",e:"Thank you for your help.",z:"三克"},
  "sorry":{p:"S AA1 R IY0",m:"對不起",e:"I am sorry.",z:"索瑞"},
  "please":{p:"P L IY1 Z",m:"請",e:"Please sit down.",z:"普利茲"},
  "yes":{p:"Y EH1 S",m:"是",e:"Yes, I can.",z:"耶斯"},
  "no":{p:"N OW1",m:"不",e:"No, thank you.",z:"諾"},
  "okay":{p:"OW0 K EY1",m:"好的",e:"Okay, let's go.",z:"歐K"},
  "name":{p:"N EY1 M",m:"名字",e:"My name is Tom.",z:"內姆"},
  "friend":{p:"F R EH1 N D",m:"朋友",e:"She is my friend.",z:"弗瑞德"},
  "number":{p:"N AH1 M B ER0",m:"號碼",e:"My number is five.",z:"南伯"},
  "color":{p:"K AH1 L ER0",m:"顏色",e:"What color is it?",z:"卡勒"},
  "shape":{p:"SH EY1 P",m:"形狀",e:"The shape is round.",z:"謝普"},
  "size":{p:"S AY1 Z",m:"尺寸",e:"What size is it?",z:"賽茲"},
  "weather":{p:"W EH1 DH ER0",m:"天氣",e:"The weather is nice.",z:"威瑟"},
  "story":{p:"S T AO1 R IY0",m:"故事",e:"Tell me a story.",z:"斯多瑞"},
  "game":{p:"G EY1 M",m:"遊戲",e:"Let's play a game.",z:"給姆"},
  "song":{p:"S AO1 NG",m:"歌曲",e:"Let's sing a song.",z:"桑"},
  "picture":{p:"P IH1 K CH ER0",m:"圖片",e:"I draw a picture.",z:"皮克雀"},
  "paper":{p:"P EY1 P ER0",m:"紙",e:"I need paper.",z:"佩柏"},
  "music":{p:"M Y UW1 Z IH0 K",m:"音樂",e:"I like music.",z:"謬茲克"},
  "world":{p:"W ER1 L D",m:"世界",e:"The world is big.",z:"沃爾德"},
  "people":{p:"P IY1 P AH0 L",m:"人們",e:"Many people are there.",z:"批剖"},
  "animal":{p:"AE1 N AH0 M AH0 L",m:"動物",e:"I like animals.",z:"安尼默"},
  "computer":{p:"K AH0 M P Y UW1 T ER0",m:"電腦",e:"I use a computer.",z:"康皮優特"},
  "question":{p:"K W EH1 S CH AH0 N",m:"問題",e:"I have a question.",z:"快斯陳"},
  "answer":{p:"AE1 N S ER0",m:"答案",e:"I know the answer.",z:"安瑟"},
  "example":{p:"IH0 G Z AE1 M P AH0 L",m:"例子",e:"This is an example.",z:"伊格贊普"},
  "problem":{p:"P R AA1 B L AH0 M",m:"問題",e:"I have a problem.",z:"普拉布冷"},
  "idea":{p:"AY0 D IY1 AH0",m:"想法",e:"That is a good idea.",z:"愛迪亞"},
  "group":{p:"G R UW1 P",m:"小組",e:"We are in the same group.",z:"古普"},
  "member":{p:"M EH1 M B ER0",m:"成員",e:"She is a member.",z:"門伯"},
  "minute":{p:"M IH1 N AH0 T",m:"分鐘",e:"Wait a minute.",z:"米尼特"},
  "hour":{p:"AW1 ER0",m:"小時",e:"One hour has 60 minutes.",z:"奧爾"},
  "week":{p:"W IY1 K",m:"星期",e:"There are seven days in a week.",z:"威克"},
  "month":{p:"M AH1 N TH",m:"月",e:"There are twelve months.",z:"忙斯"},
  "year":{p:"Y IH1 R",m:"年",e:"Happy new year.",z:"伊爾"},
  "today":{p:"T AH0 D EY1",m:"今天",e:"Today is sunny.",z:"土爹"},
  "tomorrow":{p:"T AH0 M AO1 R OW0",m:"明天",e:"See you tomorrow.",z:"土馬肉"},
  "yesterday":{p:"Y EH1 S T ER0 D EY0",m:"昨天",e:"Yesterday was fun.",z:"耶斯德爹"},
  "morning":{p:"M AO1 R N IH0 NG",m:"早上",e:"Good morning.",z:"摸寧"},
  "afternoon":{p:"AE2 F T ER0 N UW1 N",m:"下午",e:"Good afternoon.",z:"阿夫特努恩"},
  "evening":{p:"IY1 V N IH0 NG",m:"傍晚",e:"Good evening.",z:"伊夫寧"},
  "night":{p:"N AY1 T",m:"晚上",e:"Good night.",z:"奈特"},
  "time":{p:"T AY1 M",m:"時間",e:"What time is it?",z:"太姆"},
  "day":{p:"D EY1",m:"天",e:"Have a nice day.",z:"爹"},
  "date":{p:"D EY1 T",m:"日期",e:"What is the date today?",z:"爹特"},
  "cat":{p:"K AE1 T",m:"貓",e:"The cat is sleeping.",z:"凱特"},
  "dog":{p:"D AO1 G",m:"狗",e:"I have a dog.",z:"道格"},
  "fish":{p:"F IH1 SH",m:"魚",e:"The fish is swimming.",z:"費許"},
  "bird":{p:"B ER1 D",m:"鳥",e:"A bird can fly.",z:"伯德"},
  "horse":{p:"HH AO1 R S",m:"馬",e:"The horse runs fast.",z:"霍爾斯"},
  "cow":{p:"K AW1",m:"牛",e:"The cow eats grass.",z:"靠"},
  "pig":{p:"P IH1 G",m:"豬",e:"The pig is pink.",z:"皮格"},
  "chicken":{p:"CH IH1 K AH0 N",m:"雞",e:"The chicken lays eggs.",z:"奇肯"},
  "duck":{p:"D AH1 K",m:"鴨",e:"The duck is swimming.",z:"達克"},
  "sheep":{p:"SH IY1 P",m:"綿羊",e:"The sheep is white.",z:"希普"},
  "rabbit":{p:"R AE1 B IH0 T",m:"兔子",e:"The rabbit is cute.",z:"瑞比特"},
  "bear":{p:"B EH1 R",m:"熊",e:"The bear is big.",z:"貝爾"},
  "lion":{p:"L AY1 AH0 N",m:"獅子",e:"The lion is strong.",z:"萊恩"},
  "tiger":{p:"T AY1 G ER0",m:"老虎",e:"The tiger has stripes.",z:"泰葛"},
  "elephant":{p:"EH1 L AH0 F AH0 N T",m:"大象",e:"The elephant is big.",z:"愛莉芬"},
  "monkey":{p:"M AH1 NG K IY0",m:"猴子",e:"The monkey eats bananas.",z:"芒奇"},
  "snake":{p:"S N EY1 K",m:"蛇",e:"The snake is long.",z:"斯內克"},
  "mouse":{p:"M AW1 S",m:"老鼠",e:"The mouse is small.",z:"茅斯"},
  "frog":{p:"F R AO1 G",m:"青蛙",e:"The frog is green.",z:"弗羅格"},
  "turtle":{p:"T ER1 T AH0 L",m:"烏龜",e:"The turtle walks slowly.",z:"特透"},
  "butterfly":{p:"B AH1 T ER0 F L AY0",m:"蝴蝶",e:"The butterfly is colorful.",z:"巴特弗萊"},
  "ant":{p:"AE1 N T",m:"螞蟻",e:"The ant is small.",z:"安特"},
  "bee":{p:"B IY1",m:"蜜蜂",e:"The bee makes honey.",z:"比"},
  "dolphin":{p:"D AA1 L F AH0 N",m:"海豚",e:"The dolphin can swim.",z:"道芬"},
  "whale":{p:"W EY1 L",m:"鯨魚",e:"The whale is big.",z:"威爾"},
  "shark":{p:"SH AA1 R K",m:"鯊魚",e:"The shark has teeth.",z:"沙克"},
  "eagle":{p:"IY1 G AH0 L",m:"老鷹",e:"The eagle can fly high.",z:"伊狗"},
  "owl":{p:"AW1 L",m:"貓頭鷹",e:"The owl can see at night.",z:"奧爾"},
  "penguin":{p:"P EH1 NG G W IH0 N",m:"企鵝",e:"The penguin is cute.",z:"朋貴恩"},
  "fox":{p:"F AA1 K S",m:"狐狸",e:"The fox is orange.",z:"法克斯"},
  "wolf":{p:"W UH1 L F",m:"狼",e:"The wolf howls.",z:"沃夫"},
  "deer":{p:"D IH1 R",m:"鹿",e:"The deer runs fast.",z:"迪爾"},
  "goat":{p:"G OW1 T",m:"山羊",e:"The goat eats grass.",z:"勾特"},
  "donkey":{p:"D AA1 NG K IY0",m:"驢子",e:"The donkey is gray.",z:"東奇"},
  "camel":{p:"K AE1 M AH0 L",m:"駱駝",e:"The camel has a hump.",z:"凱默"},
  "parrot":{p:"P AE1 R AH0 T",m:"鸚鵡",e:"The parrot can talk.",z:"派瑞特"},
  "apple":{p:"AE1 P AH0 L",m:"蘋果",e:"I eat an apple.",z:"愛普"},
  "banana":{p:"B AH0 N AE1 N AH0",m:"香蕉",e:"I like bananas.",z:"八娜娜"},
  "orange":{p:"AO1 R AH0 N JH",m:"柳橙",e:"I like orange juice.",z:"奧倫居"},
  "grape":{p:"G R EY1 P",m:"葡萄",e:"The grapes are purple.",z:"格雷普"},
  "strawberry":{p:"S T R AO1 B EH0 R IY0",m:"草莓",e:"I like strawberries.",z:"斯綽貝瑞"},
  "bread":{p:"B R EH1 D",m:"麵包",e:"I eat bread for breakfast.",z:"布雷德"},
  "cake":{p:"K EY1 K",m:"蛋糕",e:"The cake is sweet.",z:"凱克"},
  "rice":{p:"R AY1 S",m:"米飯",e:"I eat rice.",z:"萊斯"},
  "meat":{p:"M IY1 T",m:"肉",e:"The meat is hot.",z:"米特"},
  "milk":{p:"M IH1 L K",m:"牛奶",e:"I drink milk.",z:"米爾克"},
  "water":{p:"W AO1 T ER0",m:"水",e:"I drink water.",z:"沃特"},
  "juice":{p:"JH UW1 S",m:"果汁",e:"The juice is sweet.",z:"居斯"},
  "egg":{p:"EH1 G",m:"蛋",e:"The egg is round.",z:"艾格"},
  "cheese":{p:"CH IY1 Z",m:"起司",e:"The cheese is yummy.",z:"奇茲"},
  "butter":{p:"B AH1 T ER0",m:"奶油",e:"I put butter on bread.",z:"巴特"},
  "cookie":{p:"K UH1 K IY0",m:"餅乾",e:"The cookie is sweet.",z:"庫奇"},
  "candy":{p:"K AE1 N D IY0",m:"糖果",e:"The candy is sweet.",z:"凱迪"},
  "chocolate":{p:"CH AO1 K AH0 L AH0 T",m:"巧克力",e:"I like chocolate.",z:"超克力"},
  "pizza":{p:"P IY1 T S AH0",m:"披薩",e:"The pizza is hot.",z:"批薩"},
  "hamburger":{p:"HH AE1 M B ER0 G ER0",m:"漢堡",e:"I eat a hamburger.",z:"漢伯格"},
  "sandwich":{p:"S AE1 N D W IH0 CH",m:"三明治",e:"The sandwich is good.",z:"三威區"},
  "noodle":{p:"N UW1 D AH0 L",m:"麵條",e:"I eat noodles.",z:"努斗"},
  "soup":{p:"S UW1 P",m:"湯",e:"The soup is hot.",z:"蘇普"},
  "salad":{p:"S AE1 L AH0 D",m:"沙拉",e:"The salad is fresh.",z:"薩拉德"},
  "cereal":{p:"S IH1 R IY0 AH0 L",m:"麥片",e:"I eat cereal for breakfast.",z:"西瑞歐"},
  "toast":{p:"T OW1 S T",m:"吐司",e:"I eat toast.",z:"透斯特"},
  "steak":{p:"S T EY1 K",m:"牛排",e:"The steak is good.",z:"斯戴克"},
  "potato":{p:"P AH0 T EY1 T OW0",m:"馬鈴薯",e:"I like potatoes.",z:"波貼透"},
  "tomato":{p:"T AH0 M EY1 T OW0",m:"番茄",e:"The tomato is red.",z:"土妹透"},
  "onion":{p:"AH1 N Y AH0 N",m:"洋蔥",e:"The onion makes me cry.",z:"阿年"},
  "carrot":{p:"K AE1 R AH0 T",m:"紅蘿蔔",e:"The rabbit eats carrots.",z:"凱瑞特"},
  "corn":{p:"K AO1 R N",m:"玉米",e:"I like corn.",z:"康"},
  "peanut":{p:"P IY1 N AH0 T",m:"花生",e:"I eat peanuts.",z:"批納特"},
  "jelly":{p:"JH EH1 L IY0",m:"果凍",e:"The jelly is sweet.",z:"杰力"},
  "honey":{p:"HH AH1 N IY0",m:"蜂蜜",e:"Honey is sweet.",z:"哈尼"},
  "tea":{p:"T IY1",m:"茶",e:"I drink tea.",z:"替"},
  "coffee":{p:"K AO1 F IY0",m:"咖啡",e:"I drink coffee.",z:"咖啡"},
  "cream":{p:"K R IY1 M",m:"奶油",e:"I like ice cream.",z:"克里姆"},
  "ice cream":{p:"AY1 S K R IY1 M",m:"冰淇淋",e:"I like ice cream.",z:"艾斯克里姆"},
  "pie":{p:"P AY1",m:"派",e:"The pie is delicious.",z:"派"},
  "donut":{p:"D OW1 N AH0 T",m:"甜甜圈",e:"The donut is sweet.",z:"豆納特"},
  "muffin":{p:"M AH1 F AH0 N",m:"馬芬",e:"I eat a muffin.",z:"馬芬"},
  "pancake":{p:"P AE1 N K EY1 K",m:"鬆餅",e:"I eat pancakes.",z:"潘凱克"},
  "head":{p:"HH EH1 D",m:"頭",e:"My head hurts.",z:"黑德"},
  "face":{p:"F EY1 S",m:"臉",e:"She has a pretty face.",z:"費斯"},
  "eye":{p:"AY1",m:"眼睛",e:"I have two eyes.",z:"愛"},
  "ear":{p:"IY1 R",m:"耳朵",e:"The rabbit has long ears.",z:"伊爾"},
  "nose":{p:"N OW1 Z",m:"鼻子",e:"My nose is small.",z:"諾茲"},
  "mouth":{p:"M AW1 TH",m:"嘴巴",e:"Open your mouth.",z:"茅斯"},
  "hand":{p:"HH AE1 N D",m:"手",e:"Wash your hands.",z:"漢德"},
  "arm":{p:"AA1 R M",m:"手臂",e:"He has strong arms.",z:"阿姆"},
  "leg":{p:"L EH1 G",m:"腿",e:"The cat has four legs.",z:"雷格"},
  "foot":{p:"F UH1 T",m:"腳",e:"My foot hurts.",z:"富特"},
  "hair":{p:"HH EH1 R",m:"頭髮",e:"She has long hair.",z:"黑爾"},
  "tooth":{p:"T UW1 TH",m:"牙齒",e:"Brush your teeth.",z:"土斯"},
  "finger":{p:"F IH1 NG G ER0",m:"手指",e:"I have five fingers.",z:"芬格"},
  "knee":{p:"N IY1",m:"膝蓋",e:"My knee hurts.",z:"尼"},
  "shoulder":{p:"SH OW1 L D ER0",m:"肩膀",e:"He has strong shoulders.",z:"收德"},
  "elbow":{p:"EH1 L B OW0",m:"手肘",e:"My elbow hurts.",z:"艾爾波"},
  "chin":{p:"CH IH1 N",m:"下巴",e:"She has a small chin.",z:"親"},
  "cheek":{p:"CH IY1 K",m:"臉頰",e:"Her cheeks are red.",z:"奇克"},
  "lip":{p:"L IH1 P",m:"嘴唇",e:"She has red lips.",z:"利普"},
  "tongue":{p:"T AH1 NG",m:"舌頭",e:"My tongue hurts.",z:"湯"},
  "neck":{p:"N EH1 K",m:"脖子",e:"The giraffe has a long neck.",z:"內克"},
  "toe":{p:"T OW1",m:"腳趾",e:"I have ten toes.",z:"透"},
  "red":{p:"R EH1 D",m:"紅色",e:"The apple is red.",z:"瑞德"},
  "blue":{p:"B L UW1",m:"藍色",e:"The sky is blue.",z:"布魯"},
  "green":{p:"G R IY1 N",m:"綠色",e:"The grass is green.",z:"格林"},
  "yellow":{p:"Y EH1 L OW0",m:"黃色",e:"The sun is yellow.",z:"耶婁"},
  "purple":{p:"P ER1 P AH0 L",m:"紫色",e:"The flower is purple.",z:"普普"},
  "pink":{p:"P IH1 NG K",m:"粉紅色",e:"The pig is pink.",z:"品克"},
  "white":{p:"W AY1 T",m:"白色",e:"Snow is white.",z:"外特"},
  "black":{p:"B L AE1 K",m:"黑色",e:"The cat is black.",z:"布萊克"},
  "brown":{p:"B R AW1 N",m:"棕色",e:"The dog is brown.",z:"布朗"},
  "gray":{p:"G R EY1",m:"灰色",e:"The sky is gray.",z:"格雷"},
  "gold":{p:"G OW1 L D",m:"金色",e:"The sun is gold.",z:"勾德"},
  "silver":{p:"S IH1 L V ER0",m:"銀色",e:"The moon is silver.",z:"西爾弗"},
  "one":{p:"W AH1 N",m:"一",e:"I have one book.",z:"萬"},
  "two":{p:"T UW1",m:"二",e:"I have two hands.",z:"吐"},
  "three":{p:"TH R IY1",m:"三",e:"There are three cats.",z:"斯瑞"},
  "four":{p:"F AO1 R",m:"四",e:"I have four pencils.",z:"佛"},
  "five":{p:"F AY1 V",m:"五",e:"I have five fingers.",z:"發五"},
  "six":{p:"S IH1 K S",m:"六",e:"I am six years old.",z:"希克斯"},
  "seven":{p:"S EH1 V AH0 N",m:"七",e:"There are seven days.",z:"賽文"},
  "eight":{p:"EY1 T",m:"八",e:"I am eight years old.",z:"艾特"},
  "nine":{p:"N AY1 N",m:"九",e:"I have nine toys.",z:"奈恩"},
  "ten":{p:"T EH1 N",m:"十",e:"I have ten cookies.",z:"天"},
  "mother":{p:"M AH1 DH ER0",m:"媽媽",e:"My mother is kind.",z:"媽惹"},
  "father":{p:"F AA1 DH ER0",m:"爸爸",e:"My father is tall.",z:"法惹"},
  "sister":{p:"S IH1 S T ER0",m:"姐妹",e:"My sister is young.",z:"西斯得"},
  "brother":{p:"B R AH1 DH ER0",m:"兄弟",e:"My brother is funny.",z:"布拉惹"},
  "baby":{p:"B EY1 B IY0",m:"寶寶",e:"The baby is cute.",z:"北比"},
  "family":{p:"F AE1 M AH0 L IY0",m:"家庭",e:"I love my family.",z:"發米利"},
  "grandpa":{p:"G R AE1 N P AA0",m:"爺爺",e:"My grandpa is old.",z:"格蘭帕"},
  "grandma":{p:"G R AE1 N M AA0",m:"奶奶",e:"My grandma is kind.",z:"格蘭馬"},
  "aunt":{p:"AE1 N T",m:"阿姨",e:"My aunt is nice.",z:"安特"},
  "uncle":{p:"AH1 NG K AH0 L",m:"叔叔",e:"My uncle is funny.",z:"昂扣"},
  "cousin":{p:"K AH1 Z AH0 N",m:"表兄弟姊妹",e:"My cousin is my friend.",z:"卡怎"},
  "shirt":{p:"SH ER1 T",m:"襯衫",e:"The shirt is white.",z:"射特"},
  "pants":{p:"P AE1 N T S",m:"褲子",e:"He wears blue pants.",z:"潘斯"},
  "shoes":{p:"SH UW1 Z",m:"鞋子",e:"My shoes are new.",z:"蘇茲"},
  "socks":{p:"S AA1 K S",m:"襪子",e:"I wear socks.",z:"薩克斯"},
  "hat":{p:"HH AE1 T",m:"帽子",e:"The hat is red.",z:"哈特"},
  "coat":{p:"K OW1 T",m:"外套",e:"Put on your coat.",z:"寇特"},
  "dress":{p:"D R EH1 S",m:"洋裝",e:"She wears a dress.",z:"爵斯"},
  "skirt":{p:"S K ER1 T",m:"裙子",e:"She wears a skirt.",z:"斯葛特"},
  "jacket":{p:"JH AE1 K AH0 T",m:"夾克",e:"He wears a jacket.",z:"杰凱特"},
  "glove":{p:"G L AH1 V",m:"手套",e:"I wear gloves.",z:"格拉夫"},
  "scarf":{p:"S K AA1 R F",m:"圍巾",e:"She wears a scarf.",z:"斯卡夫"},
  "belt":{p:"B EH1 L T",m:"皮帶",e:"He wears a belt.",z:"貝爾特"},
  "tie":{p:"T AY1",m:"領帶",e:"He wears a tie.",z:"泰"},
  "house":{p:"HH AW1 S",m:"房子",e:"The house is big.",z:"好斯"},
  "room":{p:"R UW1 M",m:"房間",e:"My room is clean.",z:"入姆"},
  "kitchen":{p:"K IH1 CH AH0 N",m:"廚房",e:"Mom is in the kitchen.",z:"奇陳"},
  "bedroom":{p:"B EH1 D R UW2 M",m:"臥室",e:"My bedroom is small.",z:"貝德入姆"},
  "bathroom":{p:"B AE1 TH R UW2 M",m:"浴室",e:"I take a bath in the bathroom.",z:"巴斯入姆"},
  "door":{p:"D AO1 R",m:"門",e:"Open the door.",z:"多"},
  "window":{p:"W IH1 N D OW0",m:"窗戶",e:"Open the window.",z:"溫斗"},
  "bed":{p:"B EH1 D",m:"床",e:"I sleep on my bed.",z:"貝德"},
  "table":{p:"T EY1 B AH0 L",m:"桌子",e:"The book is on the table.",z:"帖伯"},
  "chair":{p:"CH EH1 R",m:"椅子",e:"Sit on the chair.",z:"切爾"},
  "sofa":{p:"S OW1 F AH0",m:"沙發",e:"I sit on the sofa.",z:"搜法"},
  "lamp":{p:"L AE1 M P",m:"燈",e:"Turn on the lamp.",z:"蘭普"},
  "clock":{p:"K L AA1 K",m:"時鐘",e:"The clock is on the wall.",z:"柯拉克"},
  "mirror":{p:"M IH1 R ER0",m:"鏡子",e:"Look in the mirror.",z:"米若"},
  "book":{p:"B UH1 K",m:"書",e:"I read a book.",z:"布克"},
  "pen":{p:"P EH1 N",m:"筆",e:"I write with a pen.",z:"噴"},
  "pencil":{p:"P EH1 N S AH0 L",m:"鉛筆",e:"The pencil is long.",z:"噴搜"},
  "ruler":{p:"R UW1 L ER0",m:"尺",e:"My ruler is blue.",z:"魯勒"},
  "bag":{p:"B AE1 G",m:"書包",e:"My bag is heavy.",z:"拜格"},
  "teacher":{p:"T IY1 CH ER0",m:"老師",e:"The teacher is nice.",z:"提雀"},
  "student":{p:"S T UW1 D AH0 N T",m:"學生",e:"I am a student.",z:"斯丟登特"},
  "school":{p:"S K UW1 L",m:"學校",e:"I go to school.",z:"斯庫爾"},
  "desk":{p:"D EH1 S K",m:"書桌",e:"Sit at your desk.",z:"德斯克"},
  "class":{p:"K L AE1 S",m:"班級",e:"We are in the same class.",z:"克拉斯"},
  "teacher":{p:"T IY1 CH ER0",m:"老師",e:"The teacher is nice.",z:"提雀"},
  "run":{p:"R AH1 N",m:"跑步",e:"I can run fast.",z:"軟"},
  "jump":{p:"JH AH1 M P",m:"跳",e:"The frog can jump.",z:"將普"},
  "walk":{p:"W AO1 K",m:"走路",e:"I walk to school.",z:"沃克"},
  "swim":{p:"S W IH1 M",m:"游泳",e:"I can swim.",z:"斯威姆"},
  "fly":{p:"F L AY1",m:"飛",e:"The bird can fly.",z:"弗萊"},
  "eat":{p:"IY1 T",m:"吃",e:"I eat breakfast.",z:"伊特"},
  "drink":{p:"D R IH1 NG K",m:"喝",e:"I drink water.",z:"準克"},
  "sleep":{p:"S L IY1 P",m:"睡覺",e:"I sleep at night.",z:"斯利普"},
  "read":{p:"R IY1 D",m:"閱讀",e:"I read a book.",z:"瑞德"},
  "write":{p:"R AY1 T",m:"寫",e:"I write a letter.",z:"瑞特"},
  "draw":{p:"D R AO1",m:"畫畫",e:"I draw a picture.",z:"桌"},
  "sing":{p:"S IH1 NG",m:"唱歌",e:"I sing a song.",z:"星"},
  "dance":{p:"D AE1 N S",m:"跳舞",e:"She can dance.",z:"丹斯"},
  "play":{p:"P L EY1",m:"玩耍",e:"The children play.",z:"普雷"},
  "cook":{p:"K UH1 K",m:"煮飯",e:"Mom can cook.",z:"庫克"},
  "wash":{p:"W AA1 SH",m:"洗",e:"Wash your hands.",z:"瓦許"},
  "clean":{p:"K L IY1 N",m:"打掃",e:"Clean your room.",z:"克林"},
  "brush":{p:"B R AH1 SH",m:"刷",e:"Brush your teeth.",z:"布拉許"},
  "ride":{p:"R AY1 D",m:"騎",e:"I ride a bike.",z:"瑞德"},
  "drive":{p:"D R AY1 V",m:"開車",e:"Dad drives to work.",z:"拽夫"},
  "catch":{p:"K AE1 CH",m:"接",e:"Catch the ball.",z:"凱區"},
  "throw":{p:"TH R OW1",m:"丟",e:"Throw the ball.",z:"斯肉"},
  "kick":{p:"K IH1 K",m:"踢",e:"Kick the ball.",z:"奇克"},
  "sit":{p:"S IH1 T",m:"坐",e:"Sit down.",z:"西特"},
  "stand":{p:"S T AE1 N D",m:"站",e:"Stand up.",z:"斯坦德"},
  "smile":{p:"S M AY1 L",m:"微笑",e:"She smiles.",z:"斯邁爾"},
  "cry":{p:"K R AY1",m:"哭",e:"The baby cries.",z:"克萊"},
  "laugh":{p:"L AE1 F",m:"笑",e:"We laugh together.",z:"拉夫"},
  "listen":{p:"L IH1 S AH0 N",m:"聽",e:"Listen to me.",z:"利森"},
  "watch":{p:"W AA1 CH",m:"看",e:"I watch TV.",z:"瓦區"},
  "look":{p:"L UH1 K",m:"看",e:"Look at me.",z:"路克"},
  "see":{p:"S IY1",m:"看見",e:"I see a bird.",z:"西"},
  "say":{p:"S EY1",m:"說",e:"Say hello.",z:"賽"},
  "tell":{p:"T EH1 L",m:"告訴",e:"Tell me a story.",z:"特爾"},
  "call":{p:"K AO1 L",m:"打電話",e:"I call my friend.",z:"寇爾"},
  "help":{p:"HH EH1 L P",m:"幫助",e:"Can you help me?",z:"赫爾普"},
  "give":{p:"G IH1 V",m:"給",e:"Give me a book.",z:"給夫"},
  "take":{p:"T EY1 K",m:"拿",e:"Take your bag.",z:"帖克"},
  "make":{p:"M EY1 K",m:"做",e:"I make a cake.",z:"每克"},
  "know":{p:"N OW1",m:"知道",e:"I know the answer.",z:"諾"},
  "think":{p:"TH IH1 NG K",m:"想",e:"I think so.",z:"星克"},
  "want":{p:"W AA1 N T",m:"想要",e:"I want water.",z:"旺特"},
  "need":{p:"N IY1 D",m:"需要",e:"I need help.",z:"尼德"},
  "like":{p:"L AY1 K",m:"喜歡",e:"I like pizza.",z:"萊克"},
  "love":{p:"L AH1 V",m:"愛",e:"I love you.",z:"拉夫"},
  "big":{p:"B IH1 G",m:"大的",e:"The elephant is big.",z:"比格"},
  "small":{p:"S M AO1 L",m:"小的",e:"The mouse is small.",z:"斯莫爾"},
  "long":{p:"L AO1 NG",m:"長的",e:"The snake is long.",z:"浪"},
  "short":{p:"SH AO1 R T",m:"短的",e:"He is short.",z:"肖特"},
  "tall":{p:"T AO1 L",m:"高的",e:"My father is tall.",z:"套爾"},
  "fast":{p:"F AE1 S T",m:"快的",e:"The car is fast.",z:"法斯特"},
  "slow":{p:"S L OW1",m:"慢的",e:"The turtle is slow.",z:"斯摟"},
  "new":{p:"N UW1",m:"新的",e:"I have a new toy.",z:"努"},
  "old":{p:"OW1 L D",m:"舊的",e:"The house is old.",z:"歐德"},
  "young":{p:"Y AH1 NG",m:"年輕的",e:"She is young.",z:"揚"},
  "good":{p:"G UH1 D",m:"好的",e:"This is good.",z:"固德"},
  "bad":{p:"B AE1 D",m:"壞的",e:"That is bad.",z:"拜德"},
  "beautiful":{p:"B Y UW1 T AH0 F AH0 L",m:"美麗的",e:"The flower is beautiful.",z:"比優特否"},
  "ugly":{p:"AH1 G L IY0",m:"醜的",e:"The witch is ugly.",z:"阿格利"},
  "clean":{p:"K L IY1 N",m:"乾淨的",e:"The room is clean.",z:"克林"},
  "dirty":{p:"D ER1 T IY0",m:"髒的",e:"My hands are dirty.",z:"德提"},
  "hot":{p:"HH AA1 T",m:"熱的",e:"The soup is hot.",z:"哈特"},
  "cold":{p:"K OW1 L D",m:"冷的",e:"The ice cream is cold.",z:"寇德"},
  "warm":{p:"W AO1 R M",m:"溫暖的",e:"The sun is warm.",z:"沃姆"},
  "cool":{p:"K UW1 L",m:"涼爽的",e:"The water is cool.",z:"庫爾"},
  "happy":{p:"HH AE1 P IY0",m:"快樂的",e:"I am happy.",z:"嗨皮"},
  "sad":{p:"S AE1 D",m:"難過的",e:"He is sad.",z:"薩德"},
  "angry":{p:"AE1 NG G R IY0",m:"生氣的",e:"She is angry.",z:"安格瑞"},
  "hungry":{p:"HH AH1 NG G R IY0",m:"餓的",e:"I am hungry.",z:"杭格瑞"},
  "thirsty":{p:"TH ER1 S T IY0",m:"渴的",e:"I am thirsty.",z:"瑟斯提"},
  "tired":{p:"T AY1 ER0 D",m:"累的",e:"I am tired.",z:"太爾德"},
  "sweet":{p:"S W IY1 T",m:"甜的",e:"The candy is sweet.",z:"斯威特"},
  "sour":{p:"S AW1 ER0",m:"酸的",e:"The lemon is sour.",z:"嫂爾"},
  "bright":{p:"B R AY1 T",m:"明亮的",e:"The sun is bright.",z:"布萊特"},
  "dark":{p:"D AA1 R K",m:"黑暗的",e:"The room is dark.",z:"達克"},
  "loud":{p:"L AW1 D",m:"大聲的",e:"The music is loud.",z:"勞德"},
  "quiet":{p:"K W AY1 AH0 T",m:"安靜的",e:"Be quiet.",z:"快特"},
  "soft":{p:"S AA1 F T",m:"柔軟的",e:"The pillow is soft.",z:"索夫特"},
  "hard":{p:"HH AA1 R D",m:"堅硬的",e:"The rock is hard.",z:"哈德"},
  "wet":{p:"W EH1 T",m:"濕的",e:"My shirt is wet.",z:"威特"},
  "dry":{p:"D R AY1",m:"乾的",e:"The towel is dry.",z:"拽"},
  "kind":{p:"K AY1 N D",m:"親切的",e:"She is kind.",z:"凱恩德"},
  "brave":{p:"B R EY1 V",m:"勇敢的",e:"He is brave.",z:"布雷夫"},
  "shy":{p:"SH AY1",m:"害羞的",e:"She is shy.",z:"曬"},
  "strong":{p:"S T R AO1 NG",m:"強壯的",e:"He is strong.",z:"斯狀"},
  "weak":{p:"W IY1 K",m:"虛弱的",e:"I feel weak.",z:"威克"},
  "easy":{p:"IY1 Z IY0",m:"簡單的",e:"The test is easy.",z:"伊吉"},
  "difficult":{p:"D IH1 F AH0 K AH0 L T",m:"困難的",e:"This is difficult.",z:"低飛扣"},
  "fun":{p:"F AH1 N",m:"有趣的",e:"The game is fun.",z:"凡"},
  "funny":{p:"F AH1 N IY0",m:"好笑的",e:"He is funny.",z:"發尼"},
  "sun":{p:"S AH1 N",m:"太陽",e:"The sun is bright.",z:"桑"},
  "rain":{p:"R EY1 N",m:"下雨",e:"It is raining.",z:"瑞恩"},
  "cloud":{p:"K L AW1 D",m:"雲",e:"The cloud is white.",z:"克勞德"},
  "wind":{p:"W IH1 N D",m:"風",e:"The wind is strong.",z:"溫德"},
  "snow":{p:"S N OW1",m:"雪",e:"It is snowing.",z:"斯諾"},
  "sky":{p:"S K AY1",m:"天空",e:"The sky is blue.",z:"斯凱"},
  "moon":{p:"M UW1 N",m:"月亮",e:"The moon is bright.",z:"穆恩"},
  "star":{p:"S T AA1 R",m:"星星",e:"I see stars.",z:"斯達"},
  "rainbow":{p:"R EY1 N B OW0",m:"彩虹",e:"The rainbow is colorful.",z:"瑞恩波"},
  "tree":{p:"T R IY1",m:"樹",e:"The tree is tall.",z:"區伊"},
  "flower":{p:"F L AW1 ER0",m:"花",e:"The flower is pretty.",z:"弗勞爾"},
  "grass":{p:"G R AE1 S",m:"草",e:"The grass is green.",z:"格拉絲"},
  "leaf":{p:"L IY1 F",m:"葉子",e:"The leaf is green.",z:"利夫"},
  "river":{p:"R IH1 V ER0",m:"河流",e:"The river is long.",z:"瑞弗"},
  "lake":{p:"L EY1 K",m:"湖",e:"The lake is blue.",z:"雷克"},
  "ocean":{p:"OW1 SH AH0 N",m:"海洋",e:"The ocean is big.",z:"歐申"},
  "mountain":{p:"M AW1 N T AH0 N",m:"山",e:"The mountain is high.",z:"茅恩田"},
  "forest":{p:"F AO1 R AH0 S T",m:"森林",e:"The forest is big.",z:"佛瑞斯特"},
  "beach":{p:"B IY1 CH",m:"沙灘",e:"I go to the beach.",z:"比區"},
  "car":{p:"K AA1 R",m:"汽車",e:"The car is red.",z:"卡"},
  "bus":{p:"B AH1 S",m:"公車",e:"I take the bus.",z:"巴斯"},
  "train":{p:"T R EY1 N",m:"火車",e:"The train is fast.",z:"春"},
  "plane":{p:"P L EY1 N",m:"飛機",e:"The plane flies high.",z:"普連"},
  "boat":{p:"B OW1 T",m:"船",e:"The boat is on the water.",z:"波特"},
  "bike":{p:"B AY1 K",m:"腳踏車",e:"I ride my bike.",z:"拜克"},
  "truck":{p:"T R AH1 K",m:"卡車",e:"The truck is big.",z:"抓克"},
  "taxi":{p:"T AE1 K S IY0",m:"計程車",e:"I take a taxi.",z:"塔克斯"},
  "park":{p:"P AA1 R K",m:"公園",e:"I play in the park.",z:"帕克"},
  "zoo":{p:"Z UW1",m:"動物園",e:"I go to the zoo.",z:"租"},
  "store":{p:"S T AO1 R",m:"商店",e:"I go to the store.",z:"斯多"},
  "hospital":{p:"HH AA1 S P IH0 T AH0 L",m:"醫院",e:"He is in the hospital.",z:"哈斯皮透"},
  "library":{p:"L AY1 B R EH0 R IY0",m:"圖書館",e:"I read in the library.",z:"萊布瑞瑞"},
  "restaurant":{p:"R EH1 S T ER0 AA0 N T",m:"餐廳",e:"We eat at the restaurant.",z:"瑞斯掏恩特"},
  "museum":{p:"M Y UW0 Z IY1 AH0 M",m:"博物館",e:"I visit the museum.",z:"謬吉安"},
  "farm":{p:"F AA1 R M",m:"農場",e:"The farm has animals.",z:"法姆"},
  "garden":{p:"G AA1 R D AH0 N",m:"花園",e:"The garden is pretty.",z:"嘎登"},
  "market":{p:"M AA1 R K AH0 T",m:"市場",e:"We go to the market.",z:"馬凱特"},
  "airport":{p:"EH1 R P AO2 R T",m:"機場",e:"We go to the airport.",z:"埃爾波特"},
  "station":{p:"S T EY1 SH AH0 N",m:"車站",e:"The train station is big.",z:"斯帖申"},
  "theater":{p:"TH IY1 AH0 T ER0",m:"劇院",e:"We go to the theater.",z:"西亞特"},
};
